### ISSUE TITLE
403 trying to list namespaces as a non-admin

### ISSUE THREAD

**Issue by jmontleon** [konveyor/crane-ui-plugin#30]
Trying to migrate from DevSandbox to Single Node OpenShift the UI gets stopped with:

```
Cannot load source cluster namespaces Request failed with status code 403 namespaces is forbidden: User "rhn-engineering-jmontleo" cannot list resource "namespaces" in API group "" at the cluster scope
```
After discussing

- It will be common that non-admins cannot list namespaces at the cluster scope
- Projects can be listed, but they are OpenShift specific
- It looks like we can make a request to /api as a sufficient test oc input credentials
- From their we can either perform a graceful degradation, list projects, try namespaces if it fails, or get the specifed namespace if that fails. Or probably more simply just try to get the specified namespace.

**Comment by mturley** [comment]
Note: while I work on a real fix for this, in https://github.com/konveyor/crane-ui-plugin/pull/32 I added a workaround to prevent it from blocking you from continuing in the wizard when this error occurs. As long as *you* know the credentials and project name you enter are valid, the rest of the wizard should work correctly.

There may still be network errors in the background as react-query continues to retry the failed request (since it is mounted in the form state context and not just on that wizard step). These should be safe to ignore.
